/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef V0HHFITTER_ROOHYPATIA_H
#define V0HHFITTER_ROOHYPATIA_H 1

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooHypatia : public RooAbsPdf {
public:
  RooHypatia() {} ; 
  RooHypatia(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _l,
	      RooAbsReal& _zeta,
	      RooAbsReal& _fb,
	      RooAbsReal& _sigma,
	      RooAbsReal& _mu,
	      RooAbsReal& _a,
	      RooAbsReal& _n);
  RooHypatia(const RooHypatia& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooHypatia(*this,newname); }
  inline virtual ~RooHypatia() { }

protected:

  RooRealProxy x ;
  RooRealProxy l ;
  RooRealProxy zeta ;
  RooRealProxy fb ;
  RooRealProxy sigma ;
  RooRealProxy mu ;
  RooRealProxy a ;
  RooRealProxy n ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooHypatia,1) 
};
 
#endif // V0HHFITTER_ROOHYPATIA_H
