/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOONESIDEDPROFILELL
#define ROOONESIDEDPROFILELL

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooProfileLL.h" 
class RooOneSidedProfileLL : public RooAbsReal {
public:
  RooOneSidedProfileLL() {} ; 
  RooOneSidedProfileLL(const char *name, const char *title,
	      RooAbsReal& _profileLL);
  RooOneSidedProfileLL(const RooOneSidedProfileLL& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooOneSidedProfileLL(*this,newname); }
  inline virtual ~RooOneSidedProfileLL() { }

protected:

  RooRealProxy profileLL ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooOneSidedProfileLL,1) // Your description goes here...
};
 
#endif
